//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_web_car.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class server_carEntities : DbContext
    {
        public server_carEntities()
            : base("name=server_carEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<DetalleVentas> DetalleVentas { get; set; }
    
        public virtual ObjectResult<sp_VehiculosVendidosPorVendedor_Result> sp_VehiculosVendidosPorVendedor(string cedulaVendedor)
        {
            var cedulaVendedorParameter = cedulaVendedor != null ?
                new ObjectParameter("CedulaVendedor", cedulaVendedor) :
                new ObjectParameter("CedulaVendedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_VehiculosVendidosPorVendedor_Result>("sp_VehiculosVendidosPorVendedor", cedulaVendedorParameter);
        }
    }
}
